LICENSE
README.md
docs/Installation.md
package.json

Update version + docs (year and repo name)

Update version + docs

---

docs/Installation.md

* Information on unzip, unless installed.
* Restart command for Unbuntu 14.04.
* Some more details on the apache setup.

Updates of installation document

---

src/app/components/domain/domain.component.ts
src/app/services/dns-check.service.ts

Remove validate_syntax function and rename getNSips to getHostByName.

Remove validate_syntax and rename getNSips to getHostByName.

---

src/app/app.module.ts

Remove debug for routing

---

src/app/components/domain/domain.component.ts
src/app/services/dns-check.service.ts
src/environments/environment.ts

Fix display profile name (async problem) + change two api call

Fix display profile name (async problem) + change two api call

---

src/index.html

Add instruction to disable caching for index.html #22

 no-cache for index.html #22

---

src/app/services/dns-check.service.ts

Update the call to the history method in the new api

Fix history call

---

docs/FAQ/gui-faq-da.md
docs/FAQ/gui-faq-en.md
docs/FAQ/gui-faq-fr.md
docs/FAQ/gui-faq-sv.md

Fix  #28.
With the help of Google Translate, i add these lines: 
- A server that allows you to run zonemaster tests and save results using a JSON-RPC API
- Un serveur permettant l'execution des tests zonemaster, et l'historisation des resultats, au travers d'une API JSON-RPC.
- En server, der giver dig mulighed for at køre zonemaster-test og gemme resultater ved hjælp af en JSON-RPC API
- En server som låter dig köra zonmastertester och spara resultat med ett JSON-RPC API

Improve zonemaster description in FAQ

---

package-lock.json
package.json
scripts/selenium/local.runner.js
scripts/selenium/parallel_local.conf.js
src/app/components/form/form.component.html
src/test.ts
tests/local/local_test.js

Not a full response to #26, but this is a solution to select a list of supported browser.
Here some selenium test with a pre implementation of the BrowserStack plateform link to run parallel tests.

Add some e2e test with selenium (only works on local)

---

docs/Installation.md

Fix #9 
I add FreeBSD installation process and fix a mistake for debian bash command.
It's not tested

FreeBSD Installation process

---

docs/Installation.md

* Corrected path for included configuration files.
* Added needed enabling of modules in Apache.
* Removed uneeded use of wget for fetch instead (and removed
installation of wget)
* Editorial updates
The current instructions are incomplete or wrong.

Updated installation instructions on FreeBSD:

---

Changes
docs/Installation.md
package-lock.json
package.json
src/environments/environment.prod.ts
src/environments/environment.ts

* Updates: 
* Changes
* package-lock.json
* environment.prod.ts
* environment.ts
* package.json
* Installation.md

Preparation for release v3.1.0

---

README.md

Explain CORS in Readme
Fix #52

Explain CORS in Readme

---

src/assets/i18n/da.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/assets/i18n/sv.json

In the advanced options of the main form, i change the Digest title to Delegation Signers.
#60 
@matsduf Please check for SV and DA. thx

change Digest to Delegation Signers (DS records)

---

src/app/components/domain/domain.component.html
src/app/components/domain/domain.component.ts
src/app/components/form/form.component.css
src/app/components/form/form.component.html
src/app/components/form/form.component.ts

Add buttons to clean state of the main form.
We also clean the state  after the end of a test.
Fix #58

Clean domain check form

---

docs/Installation.md

This is basically some tidying up of formatting. A fix for inconsistent numbering is also included.

Formatting

---

docs/FAQ/gui-faq-en.md

There were many things in the FAQ to correct and it is urgent to do it for the upcoming release.

Updated FAQ (English)

---

src/app/components/form/form.component.html

a lot DNSSEC tools publish just protocol numbers of algorithm and digest and not the name.
this patch adds them.

adding numbers of algorithm and digest for convenience

---

LICENSE
src/app/components/footer/footer.component.html

Updated to correct brand name

---

src/app/components/form/form.component.html

Reverts zonemaster/zonemaster-gui#94
Merge to master instead of develop - revert to then apply it to develop branch

Revert "adding numbers of algorithm and digest for convenience"

---

docs/FAQ/gui-faq-sv.md

This is an updated translation of the FAQ. It resolves issue #90.

Update of Swedish FAQ

---

src/assets/i18n/da.json

Added space where it should be to make output correct.

Added space after string

---

docs/Installation.md

Updated installation instruction for FreeBSD

---

Changes
docs/Installation.md
package.json
src/environments/environment.prod.ts
src/environments/environment.ts

* Updated Changes file
* Updated file path in Installation document (version)
* Updated program verison in packages.json,
environment.prod.ts and environment.ts
* Corrected license in packages.json

Preparation for release of v2019.2 on GUI

---

.travis.yml
e2e/FR19.e2e-spec.ts
e2e/FR20.e2e-spec.ts
e2e/FR21.e2e-spec.ts
package-lock.json
package.json

The travis configuration was old. I update for the last supported by travis distribution (Bionic, 18.04) and to the last nodejs LTS version (14).
After that, i also make some small modifications to the tests to be able to adapt to small changes (accept a delay of few secs in some actions).
This PR fix the last issue with travis testing.

Fix travis failure and update tests consequently

---

docs/Installation.md

Missing link in installation file + typo fixed

Fix documentation

---

docs/Installation.md

This PR contains an assortment of small improvements to the Debian/Ubuntu installation instruction. It's mostly superficial and none of it is critical. I've only tested it on Debian (9 and 10). We could include it in this release or merge it after the release.

Updated installation for Debian/Ubuntu

---

Changes
docs/Installation.md
package.json
src/environments/environment.prod.ts
src/environments/environment.ts

* Changes: Updated with changes since last release.
* Installation.md: Updated version string
* package.json, environment.prod.ts and environment.ts: Set new version in code

For release v2020.1 (GUI)

---

.travis.yml
Changes
docs/FAQ/gui-faq-da.md
docs/FAQ/gui-faq-fr.md
docs/Installation.md
e2e/FR16.e2e-spec.ts
e2e/FR19.e2e-spec.ts
e2e/FR20.e2e-spec.ts
e2e/FR21.e2e-spec.ts
package-lock.json
package.json
src/app/components/domain/domain.component.html
src/app/components/domain/domain.component.ts
src/app/components/footer/footer.component.ts
src/app/components/form/form.component.html
src/app/components/form/form.component.ts
src/app/components/navigation/navigation.component.html
src/app/components/result/result.component.html
src/app/components/result/result.component.ts
src/app/services/dns-check.service.ts
src/assets/i18n/da.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/assets/i18n/sv.json
src/environments/environment.prod.ts
src/environments/environment.ts

Created by release process as updated by https://github.com/zonemaster/zonemaster/pull/906:
git checkout -b merge-develop-into-master origin/develop
git reset --soft origin/master
git commit -m 'Update master to state of develop'
git merge origin/develop

Merge develop into master

---

docs/FAQ/gui-faq-fr.md

Update FAQ (French)

---

src/app/components/navigation/navigation.component.ts

Do not blindly use the browser language. Verify that the GUI supports it, or force English.
Addresses https://github.com/zonemaster/zonemaster/issues/918
Closes #168

Check if browser language is supported

---

src/assets/i18n/da.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/assets/i18n/sv.json

Alignment error spotted while reviewing #184.
_Reminder before merging:_ if #184  and #185 are merged before this PR, check if the translation files (fi.json and nb.json) are misaligned and correct them accordingly in this PR.

Fix alignment and indentation

---

package.json
src/app/app.module.ts
src/app/components/navigation/navigation.component.html
src/app/components/navigation/navigation.component.ts

This replaces the part of #165 that adds Norwegian (nb) to GUI (ac535b1). It is the same change with the additional change that #169 introduced.
This PR should not be merged until #163 has been resolved.

Add norwegian (nb)

---

Changes
docs/Installation.md
package.json
src/environments/environment.prod.ts
src/environments/environment.ts

Updates for new version 3.3.0:
* Changes
* Installation.md
* package.json
* environment.prod.ts
* environment.ts

Prepares for release of v2021.1 (GUI)

---

.travis.yml
e2e/FR22.e2e-spec.ts
e2e/FR24.e2e-spec.ts

pin webdriver version

---

docs/Installation.md

Unify the instructions with those for Engine (for FreeBSD) and to make copy-and-past easier,
* Adds the same pkg setting as in Zonemaster-Engine.
* Updates to make copy-and-past easier.
Perform an installation on FreeBSD.

Updates installation instruction for FreeBSD

---

.travis.yml

Update version to the supported one
https://github.com/zonemaster/zonemaster/pull/1017
* Update travis configuration to match required environment
* run travis

update node version

---

Changes
docs/Installation.md
package.json
src/environments/version.ts

Prepartion for release.
Updated files:
* Changes
* docs/Installation.md
* package.json

Preparation for v2021.2.1 release (GUI)

---

package-lock.json
src/app/components/form/form.component.html
src/app/components/form/form.component.ts

Remove trailing spaces and dots on domains
#249 
* rename form variable (just for clarity)
* remove trailing spaces / dots and leading spaces
* submit a test with trailing spaces or dots in domain and / or NS
* check that the test does not crash
* the form inputs should contain the updated value

Fix trailing dots spaces

---

src/app/components/domain-check/domain-check.component.ts
src/app/components/faq/faq.component.ts
src/app/components/form/form.component.ts
src/app/components/result/result.component.ts

Update the page title base on component displayed.
\-
* Change title when browsing the FAQ.
* Display tested domain when a test in ongoing or when displaying the results.
* Create a new test, check that the domain is display in the title.
* When testing another domain from the result page, the title should change as soon as the other test starts.
* Go back in your browser history to see the first test.
* The title should contain the first domain.
* Go back again.
* The title should be back to "Zonemaster".
* Go to the FAQ.
* The title should contain "FAQ".

update page title based on route

---

src/assets/i18n/sv.json

This PR corrects the translation to Swedish in one message.
Check that it is correct.

Corrects the translation to Swedish

---

docs/Configuration.md
src/assets/app.config.sample.json

Better document the `pollingInterval` setting.
\-
* add default polling interval to the example configuration
* document the default polling interval
N/A

Add pollinginterval sample conf

---

Changes
docs/Installation.md
package.json
src/environments/version.ts

For release.
Changes "docs/Installation.md", "package.json" and "src/environments/version.ts"

Preparation release v2022.1 (GUI)

---

Changes
docs/Installation.md
package.json
src/environments/version.ts

See https://github.com/zonemaster/zonemaster/blob/develop/docs/internal-documentation/maintenance/ReleaseProcess-release.md#16-merge-develop-branch-into-master
This will be merged without needing approval.

Merge develop into master (GUI)

---

docs/API.md

This PR provides a definition of an API for Zonemaster-GUI. The API is being implemented by #334.
This is documentation only. The document should be used to verify the implementation.

GUI API document

---

scripts/create_release.js

add license to distribution archive
#366 
add license to distribution archive
```
% npm run release
% unzip -l zonemaster_web_gui.zip | grep LICENSE
1905  2021-09-08 14:28   LICENSE
```

Add license to distribution archive

---

README.md

The LICENSE file is the same in all respositories. This PR makes the wording in the reference to the file the same. 
https://github.com/zonemaster/zonemaster-backend/pull/1059
https://github.com/zonemaster/zonemaster-cli/pull/288
https://github.com/zonemaster/zonemaster-engine/pull/1152
https://github.com/zonemaster/zonemaster-ldns/pull/159
This changes documentation only.

Update the license wording to unify with the other repositories

---

docs/TranslationGuide.md
package.json
src/app/components/footer/footer.component.ts
src/app/components/form/form.component.html
src/app/components/history/history.component.html
src/app/components/result/result.component.html
src/app/components/result/result.component.ts
src/app/components/run-test/run-test.component.ts
src/locale/messages.da.xlf
src/locale/messages.es.xlf
src/locale/messages.fi.xlf
src/locale/messages.fr.xlf
src/locale/messages.nb.xlf
src/locale/messages.sv.xlf
src/locale/messages.xlf

Update french translation
Base on #370 
* Update some translated strings
* Translated untranslated strings
\-

Update fr translation

---

docs/FAQ/gui-faq-nb.md

This is an update of the Norwegian FAQ
This PR is a solution to issue #356 
...
...

Translation update 2022 11 11

---

docs/FAQ/gui-faq-es.md

Update to match original english FAQ update (#347). 
Fixes #357

Spanish FAQ Translation update

---

Changes
docs/Installation.md
package.json
src/environments/version.ts

Updates for release v2022.2.
Updates Changes, docs/Installation.md, package.json and src/environments/version.ts.
Review Changes and Installation.md. Inspect package.json and src/environments/version.ts.

Prepare release v2022.2 (GUI)

---

docs/FAQ/gui-faq-sv.md

This PR provides an updated translation of  FAQ into Swedish.
Read and review.

Update the Swedish translation of FAQ

---

Changes
docs/Installation.md
package.json
src/environments/version.ts

Updates for release v2022.2.1.
Updates: 
* Changes
* docs/Installation.md
* package.json
Review the updates.

Updates for release v2022.2.1 (GUI)

---

src/locale/messages.es.xlf

Update of spanish translation messages.es.xlf file.
Fixes #393
src/locale/messages.es.xlf

Update translation of strings to Spanish (GUI) #393

---

Changes
docs/Installation.md
package.json
src/environments/version.ts

Prepares for release v2022.2.2
Updates the following files:
* Changes
* docs/Installation.md
* package.json
Review.

Preparation for release v2022.2.2 (GUI)

---

src/app/components/footer/footer.component.html
src/locale/messages.da.xlf
src/locale/messages.es.xlf
src/locale/messages.fi.xlf
src/locale/messages.fr.xlf
src/locale/messages.nb.xlf
src/locale/messages.sv.xlf
src/locale/messages.xlf

Extract new translatable strings.
I forgot to tag the two new strings in #403 as translatable.
* Tag the new string as translatable.
* Extract the strings to have them in the translation files.
* Translate the French strings.
\-

add missing strings to translation files

---

src/locale/messages.fi.xlf

This PR provides an updated translation of the GUI strings in Finnish provided by @samisalmensuo.
The following strings are still untranslated:
```
First
Previous
Next
Last
Source code
Documentation
```
Resolves #392
Review the translation.

Updates the translation of GUI strings into Finnish

---

src/locale/messages.sv.xlf

This PR updates the GUI strings to Swedish.
Review the translation and ensure that everything has been translated.

Updates GUI strings to Swedish

---

src/locale/messages.es.xlf
src/locale/messages.nb.xlf

This PR updates translations to Norwegian and Spanish.
Resolves #421.
The XLF files.
Review the XLF files and the display in GUI.

Updates translations (GUI strings)

---

docs/FAQ/gui-faq-fi.md

This PR provides an updated translation of the FAQ in Finnish provided by @samisalmensuo.
Resolves #358.
Review the text or formal aspects of the FAQ.

Updates the translation of FAQ into Finnish

---

docs/FAQ/gui-faq-da.md
src/locale/messages.da.xlf

This PR...
Fixes #390 #391 
...
...

Update gui-faq-da.md & messages.da.xlf

---

Changes
package.json
src/environments/version.ts

Preparation for release.
Updates files `Changes`, `package.json` and `src/environments/version.ts`
Review the changes.

Preparation for release v2023.1 (GUI)

---

Changes
package.json
src/environments/version.ts

Preparation for release.
Updates files `Changes`, `package.json` and `src/environments/version.ts`
Updates to the installation document will be done in the zonemaster/zonemaster repository.
Review the changes.

Preparation for release v2023.1.4 (GUI)

---

Changes
package.json
src/environments/version.ts

Preparation for release.
Updates files `Changes`, `package.json` and `src/environments/version.ts`
Review the changes.

Preparation for release v2023.2 (GUI)

---

Changes
package.json
src/environments/version.ts

Preparation for release. Version incremented compared to #468
Updates files `Changes`, `package.json` and `src/environments/version.ts`
Review the changes.

Preparation for release v2023.2 (GUI), updated with new version

---

Changes
package-lock.json
package.json
src/app/components/footer/footer.component.html
src/environments/version.ts

This PR updates dependencies (`package.json`) to reduces warnings when building. It also includes the resulting `package-lock.json` to cache the result of `npm audit fix`.
This PR is built on top of  commit 2c299b36fc956b26b1086d9ee8d26ddeb8d40707 in #484, and the files from that are not included in this PR.
* package.json
* package-lock.json
Verify that resulting package runs well. Use the zip file enclosed in the comment below.

Updates dependencies for v2024.2 (v4.3.1)

---

Changes
package.json
src/environments/version.ts

This PR is a preparation for v2024.2.1 release. 
*  package.json
* Changes
If #482 is updated (made complete) before this is merged, then the text in changes on #482 `Changes` could be updated.
Review.

Preparation for v2024.2.1 release (GUI)

---

Changes
angular.json
e2e/FR05.e2e-spec.ts
package.json
src/assets/app.config.sample.json
src/environments/common.ts
src/environments/version.ts
src/locale/messages.sl.xlf
zonemaster.conf-example

https://github.com/zonemaster/zonemaster/blob/develop/docs/internal/maintenance/ReleaseProcess-release.md#15-merge-develop-branch-into-master
This PR needs no review.

Merge release branch into master (GUI)
