- src/app/components/result/result.component.css
The expandable lines can be expanded by clicking on them.
Set a "pointer" cursor (aka "click cursor") for such lines, so user is aware he can click on them.
> Update result CSS: set a cursor pointer on expandable results

- src/app/components/form/form.component.html
Fix #8 - Change HTML DS types (keytag and digest) from String to Int as expected in the API.
Replace html value for select options to angular [value] which cast string to int.
> Fix #8 - Change HTML DS types (keytag and digest) from String to Int as expected in the API

- Changes
- docs/Installation.md
- package.json
- src/environments/environment.prod.ts
- src/environments/environment.ts
When releasing 3.0.0 I mixed the git tags up. I want to bump the version to get it right. Now the installation script points at wrong tag, i.e. wrong version.
> Preperation for release of v3.0.1, fixing installation link.

- src/app/app.module.ts
- src/app/components/domain/domain.component.html
- src/app/components/domain/domain.component.ts
- src/app/components/form/form.component.css
- src/app/components/form/form.component.html
- src/app/components/form/form.component.ts
- src/app/components/navigation/navigation.component.html
- src/app/components/result/result.component.ts
Fix #6.
As discussed previously, i removed the pre delegated test. 
The home page now display the "options" button. All the code is exactly the same. The diff between delegated and un delegated test is done by the backend depending of the presence (or not) of the nameserver value in the api request.
Screenshot:
https://screenshots.firefox.com/WcnG0lg41nUqOgEw/localhost
> remove predelegated test page and merge all form options

- src/app/components/result/result.component.html
Fix #33.
Now the action buttons of the result page (history, share, settings, etc.) are expand by default. And so, i removed the collapse animation which is now useless.
Result (expire in 14days) : 
https://screenshots.firefox.com/w28iXn8orpxzM5RG/localhost
> Expand the collapsed action buttons of the result page.

- src/app/components/form/form.component.html
- src/app/components/form/form.component.ts
In order to use custom nameservers, we now accept if the ip is empty but the name is now required.
Same behavior for digest and keytag. 
The user can't run a test (click on the button) during the "fetch data from parent zone" query.
If the user click two or more times on the button "fetch data from parent zone", we only keep the last result. 
Fix #38
> Fix 38 undelegated test broken

- src/app/components/form/form.component.ts
Fix sending empty ns when the advanced options are not open
> Fix sending empty ns when the advanced options are not open

- docs/Installation.md
Release testing is more streamlined if the `unzip` refers to the same file name as the file created by the `npm run release` command.
> Improved cut'n'paste friendliness for release testing

- docs/Installation.md
Ubuntu 14.04 has reached its end of life and we don't support it anymore.
> Stop referring to unsupported OS version

- src/app/components/alert/alert.component.html
- src/app/components/alert/alert.component.ts
Try to improve the fix for #39 and  #40.
Now the alert message will always appear just after the navbar.
Screenshot:
https://screenshots.firefox.com/ZB6NI3YhPZqX7zuK/localhost
> Add handler for scroll event to alert message

- src/app/app.module.ts
Fix #71 
Allow using /test/:test_id or /result/:test_id to get result of a old test
> redirect all history call from test to result

- src/app/components/form/form.component.html
- src/app/components/form/form.component.ts
Pre-populated field after "fetch data from parent zone" can be deleted
Fix #59
> Pre-populated field after "fetch data from parent zone" can be deleted

- src/assets/faqs/.gitkeep
Add an empty file to force git to keep the folder "faqs". The folder is needed during the generation of faqs files
Fix #109
> Create empty dir for faqs generation

- src/tsconfig.app.json
Update tsconfig.app.ts file in order to be compliant with the new angular core engine, ivy.
It removes the WARNING message:
`WARNING in zonemaster-gui/src/environments/environment.prod.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.`
> update tsconfig for ivy engine

- src/app/components/navigation/navigation.component.css
fix #114 issue: "Language switch goes to Github instead #114"
Now, we hide the github icon when the screen is less than 1300px which fix the issue.
> fix(nav): remove github icon when the size is under 1300px to avoid lang issue

- docs/Installation.md
Program `unzip` is required for installation but is not available by default in Ubuntu 18.04.
The change is not strictly needed, but the instructions will be simpler if `unzip` is always included for installation and no extra comment is needed.
> Adding missing unzip for installation on Ubuntu/Debian

- src/app/components/navigation/navigation.component.html
Change "SV" to "DA" in the select lang form for small screen (smartphone)
Fix issue #138
> fix(#138): Change sv to da value in the lang form

- .travis.yml
- e2e/FR19.e2e-spec.ts
- e2e/FR20.e2e-spec.ts
- e2e/FR21.e2e-spec.ts
- package-lock.json
- package.json
- src/app/components/domain/domain.component.ts
- src/app/components/footer/footer.component.ts
- src/app/components/form/form.component.html
- src/app/components/form/form.component.ts
- src/app/components/result/result.component.html
- src/app/components/result/result.component.ts
- src/app/services/dns-check.service.ts
- src/assets/i18n/da.json
- src/assets/i18n/en.json
- src/assets/i18n/fr.json
- src/assets/i18n/sv.json
Like PR #116, this PR try to improve I18n support by using some new tool to align the translation files ({en,fr,da,sv}.json) to the code.
In order to use ngx-extractor, we need to use correctly our translator tool. So, I update some piece of codes to correctly use the translator service (this.translateService.get()).
I add two commands to the project:
-  i18n:init : Create a template.json file with all keys used in the code 
- i18n:extract: Update {en,fr,da,sv}.json files with news keys if detected or delete used ones.
to use these command, simply run `npm run i18n:extract` for example.
> Improve i18n

- docs/FAQ/gui-faq-da.md
- docs/FAQ/gui-faq-fr.md
- e2e/FR16.e2e-spec.ts
- src/app/components/domain/domain.component.html
This updates the fragment value in the notice box to link to the proper FAQ section.
This should fix #147
> Fix fragment in notice box

- src/index.html
It looks like the Prism stylesheet is not used anywhere. So it seems safe to remove it.
Fixes #151
> Remove third party stylesheet

- docs/Installation.md
The instruction is updated to:
* Relieve users of from having to figure out that they need to disable/configure SELinux and how to do it.
* Enable remote access to the Web GUI by opening up the firewall.
* Clarify that editing zonemaster.conf is optional, and provide a cut-and-pasteable command.
* Give more feedback and require less interaction.
* Fix the headings.
> Centos installation

- docs/TranslationGuide.md
This PR contains the same changes to TranslationGuide.md as #165 with the addition of documenting the new places where language code is set that #169 introduced. In addition comment to retain alphabetical order is added.
#165 will be closed when the remaining of it has been moved to a new PR.
This is an update of the document for upcoming translation work.
> Updates TranslationGuide

- .gitignore
With the current .gitignore, the `docs/FAQ/gui-faq-*` files are erroneously ignored. They must not be ignored.
* Makes the FAQ md files being not ignored.
* Specifies the path to generated FAQ html files to be ignored.
* Adds emacs backup files to be ignored.
> Corrects git ignore

- src/app/components/history/history.component.html
- src/app/components/result/result.component.html
This updates the date format to `YYYY-mm-dd HH:MM UTC` everywhere (in the result page and the history).
This requires that the Backend sends the `creation_time` in UTC (which is not the case with SQLite yet, see https://github.com/zonemaster/zonemaster-backend/pull/732)
Angular documentation on date formats : https://angular.io/api/common/DatePipe
Addresses #189
> Consistent date format

- docs/FAQ/gui-faq-da.md
- docs/FAQ/gui-faq-en.md
- docs/FAQ/gui-faq-fr.md
- docs/FAQ/gui-faq-sv.md
- docs/TranslationGuide.md
- src/app/components/faq/faq.component.css
As stated in #149, when using the FAQ table of content to go to a specific section, the section title is hidden behind the navbar. This is a tweak to avoid this behavior. And unlike stated in #149, this affects all devices (not only small end devices).
Fixes #149 
Before :
1. go to the FAQ : https://zonemaster.net/faq
2. reduce the size of your browser
3. choose a section for instance section 6 : https://zonemaster.net/faq#q6
4. part or all the section is hidden behind the navbar
With this PR :
4. the section now appears below the navbar
> Tweak to put links just below the navbar

- docs/TranslationGuide.md
- e2e/FR05-da.e2e-spec.ts
- e2e/FR05-en.e2e-spec.ts
- e2e/FR05-fi.e2e-spec.ts
- e2e/FR05-fr.e2e-spec.ts
- e2e/FR05-nb.e2e-spec.ts
- e2e/FR05-sv.e2e-spec.ts
* Added test script for da (Danish) language
* Added test script for fi (Finnish) language
* Added test script for nb (Norwegian) language
* Renamed language test scripts to be FR05-xx to make it possible
to expand with new language and keep them in sequence
Partially resolves request in https://github.com/zonemaster/zonemaster-gui/pull/174#pullrequestreview-633479423
> Updated e2e language tests

- docs/Installation.md
When downloading the zip file, we should follow redirection set by Github in order to get the zip file and not an HTML file.
Updates an Installation command.
Before:
1. run `curl -O https://github.com/zonemaster/zonemaster-gui/releases/download/v3.3.0/zonemaster_web_gui.zip`
2. `file zonemaster_web_gui.zip` gives `HTML document`
After :
1. run `curl -L -O https://github.com/zonemaster/zonemaster-gui/releases/download/v3.3.0/zonemaster_web_gui.zip`
2. `file zonemaster_web_gui.zip` gives `Zip archive data`
> Follow Github redirection in Installation instruction

- e2e/FR22.e2e-spec.ts
- src/app/interceptors/mock.interceptor.ts
As the client version changed, the `start_domain_test` request was not mocked resulting on all subsequent request to not be mocked as well.
The e2e test FR22 start a test, all request to the API are intercepted and the ones that matches (equality check) the requests in mock.interceptor.ts are mocked. As the client version is part of the request not having the same will result in the requests not being mocked during the tests, which can lead to inconsistency.
Use the current client version/id in the interceptor.
`npm run ng e2e -- --webdriver-update=false --specs=e2e/FR22.e2e-spec.ts`
> update client version in mock

- src/app/components/form/form.component.html
The hash algorithm for DS is often displayed as a number, e.g. with `dig`. In the GUI when you do a undelegated test and select DS parameter the hash algorithm is selected by name. It should be possible to start with the algorithm code.
This RP updates the select list so that the hash algorithm code is also shown. The solution is the same as for the DNSKEY algorithm select list.
Verify that correct algorithm is selected.
> Makes DS hash algorithm number explicit

- src/app/components/form/form.component.html
- src/app/components/form/form.component.ts
Display placeholder on DS select
Fix #226
Use -1 as default instead of `''`
Open the advanced option menu and check that all selects have a placeholder.
> Fix DS placeholder

- e2e/FR05-da.e2e-spec.ts
- e2e/FR05-en.e2e-spec.ts
- e2e/FR05-fi.e2e-spec.ts
- e2e/FR05-fr.e2e-spec.ts
- e2e/FR05-nb.e2e-spec.ts
- e2e/FR05-sv.e2e-spec.ts
- e2e/FR16.e2e-spec.ts
- e2e/utils/app.utils.ts
- src/app/components/navigation/navigation.component.css
- src/app/components/navigation/navigation.component.html
- src/app/components/navigation/navigation.component.ts
Improve language selection nav on wide screens.
Some tests (FR16) are failing because the lang has not been changed when the test is conducted. Tries to wait (after the selected language has changed) for the translation to be effective before continuing. (replace #225)
Addresses #212, #213 and #223.
* Change languages and hover links.
* `npm run ng e2e -- --webdriver-update=false --specs=e2e/FR16.e2e-spec.ts `
* `npm run ng e2e -- --webdriver-update=false --specs='e2e/FR05-*.ts'`
> Improve language selection nav

- e2e/FR08.e2e-spec.ts
- e2e/FR10.e2e-spec.ts
- e2e/FR21.e2e-spec.ts
- e2e/utils/app.utils.ts
- src/app/components/navigation/navigation.component.ts
Remember the language so someone who change it does not have to set it each it they use zonemaster.
Addresses #229
Stores the language in local storage and retrieves it at load time. If no language is found is storage defaults on the browser language.
* Change the language
* Reload
* Check that the selected language is the same
> store language in local storage

- e2e/FR22.e2e-spec.ts
- src/app/components/result/result.component.html
- src/app/components/result/result.component.ts
When someone changes the language once the results are displayed, if one of the module is expended then is will be collapsed.
This PR changes the behaviour of the result component to not re-collapse modules if the language has changed. 
When the result id changes the behaviour remains the same as before.
* Open a test results (ex. http://localhost:4200/result/df0aa98ff4e53b99 if your dev environment point to zonemaster.net)
* Expend a module
* Change the language
* If the module remains expended, it is working as expected
* Now try to change the result id by displaying another test from the history
* If all modules are now collapsed, it is working as expected
> don't collapse expended modules when language changes

- src/app/components/result/result.component.html
Fix the critical message count in the result component.
This counter was never displayed.
Try testing a non existing domain, the backend should return 2 critical messages, check that the badge next to "Critical" really display "2".
> fix critical messages count

- src/app/components/result/result.component.html
Currently the result page highlight the test number more than the domain name. This looks like an odd choice as we don't use this number anywhere. This PR removes the test number and highlights the domain instead.
This test id also leaks the number of tests in database.
n/a
* Removes the test number
* Highlights the domain name
Verify that only the domain name is displayed.
> Remove the test number in the results

- src/app/components/result/result.component.css
- src/app/components/result/result.component.html
This is a suggestion to have less colors on the UI. This is also about sharing the code I wrote for https://github.com/zonemaster/zonemaster-gui/issues/153#issuecomment-811107482
Try to address #150, #153
* Removes the line number in the result array
* Set new column width
* Defines new colors
| Level | color |
| --- | --- |
| INFO | `#66ad54` |
| NOTICE | `#007bff` |
| WARNING | `#ff9019` |
| ERROR | `#ec3545` |
| CRITICAL | `#ec3545` |
Only affecting CSS, the testing is made visually.
> [proposal] Removing background colors in results array and buttons

- src/app/components/faq/faq.component.ts
- src/app/components/result/result.component.ts
Fix subscription leaks
Fixes #262
Unsubscribe needed subscription when the component is destroyed.
* Changing the language after visiting the FAQ while not being on the FAQ page should not result in the application querying the FAQ.
* Same thing for a test result.
> unsubscribe on component ondestroy

- src/app/components/domain/domain.component.ts
Allows for easy copy/paste from the url bar and also push the url in the browser history.
* Change the url to the test result when the test is done. 
* This **does not** route the user to the result screen, this way it is still possible to make another test without going back.
* Make a test
* Check that the url has change to the result url
* Test that it is still possible to run another test without navigating to another page
* Test that you can go back / forward in the browser history
> change url when test is done

- e2e/utils/app.utils.ts
Make running e2e tests more reliable.
Now that the language nav is populated dynamically from the configuration, the tests can fail as the elements to change the language do not exists at the time of the click.
Try to wait for the languages list to be loaded.
Run the e2e tests
> wait for the lang nav before clicking

- e2e/FR25.e2e-spec.ts
- src/app/components/result/result.component.css
- src/app/components/result/result.component.html
- src/app/components/result/result.component.ts
This PR is a proposal to avoid using the modal window for the "Share" and "Export" buttons.
This also adds an icon to copy the link to the clipboard.
Addresses #238
Once you click, if the URL has been copied, you get the following visual feedback:
this one otherwise:
1. copy/paste a garbage text
2. click on the "Share" button
2. click on the "copy" icon
3. you should get a green check icon
4. paste somewhere what is in the buffer
5. you should get the link (and not the garbage text)
> Avoid using modal window

- docs/Installation.md
- src/.htaccess
- src/app/components/domain/domain.component.ts
- src/app/components/faq/faq.component.ts
- src/app/components/result/result.component.ts
Make the GUI capable of being served from a custom base URL.
Addresses #250 
* Fixes some dynamically built URLS.
* Add documentation for a custom installation
* Change the API endpoint to be `/zonemaster/api` in the prod environment file
* Build the app with `npm run build -- --base-href "/zonemaster/"`
* Serve the statics file using the following configuration (apache)
```apache
<VirtualHost *:80>
DocumentRoot /path/to/zonemaster-gui/dist
DirectoryIndex index.html
ServerAdmin example@example.net
ServerName localhost
<Directory "/path/to/zonemaster-gui/dist">
Options Indexes MultiViews FollowSymlinks Includes
AllowOverride All
Require all granted
</Directory>
ProxyPass /zonemaster/api http://localhost:5000/
ProxyPassReverse /zonemaster/api http://localhost:5000/
ProxyPreserveHost On …
```
> Serve GUI from custom base url

- src/app/components/form/form.component.ts
- src/app/interceptors/mock.interceptor.ts
- src/app/services/dns-check.service.ts
Translate backend validation errors
Depends on https://github.com/zonemaster/zonemaster-backend/pull/891, addresses #239
* Add language in param for start_domain_test and fetch_data_from_parent_zone
* Resend form if the form has been touched by the user and is in a invalid state
* Fill garbage in the test form and submit it.
* Check that errors are displayed in the selected language (if supported by the backend)
* Change the language
* Check that the errors have also been translated
> Translate backend validation errors

- docs/Installation.md
Ubuntu is not explicitly stated in the covered OSs.
Fix missing OS.
Update the installation document.
Documentation only. Nothing to test.
> Missing Ubuntu OS in link

- src/app/components/form/form.component.html
Some placeholders are not properly translated (due to limitation from the browser). Removing the hidden HTML property would fix this issue.
Addresses #277 
Remove the hidden property.
Repeat this on Firefox, Chrome and mobile device:
1. open the options
2. change the language
3. check that the "Algorithm" and "Digest type" are properly translated
> Properly translate all placeholders

- docs/Installation.md
Update the installation instruction for Rocky Linux.
This is done as part of the release testing for v2021.2.
Just replace CentOS with Rocky Linux and yum with dnf.
N/A
> Replace CentOS with Rocky Linux

- src/app/components/result/result.component.ts
Show higher severity level messages first.
Suggested as a workaround for issue #118
The message or sorted in place by severity before being displayed.
Test a domain that output different message with different severity level.
Output bellow generated by testing `ppsfleet.navy` in undelegated mode, the data was fetched from the nameserver, `ns3.ppsfleet.navy` removed from the ns list and `fake.ppsfleet.navy` pointing to 127.0.0.1 was added.
> Sort messages by severity

- docs/Configuration.md
- src/app/components/domain-check/domain-check.component.ts
- src/environments/common.ts
- src/environments/environment.tests.ts
Speed up e2e tests that start domain tests.
The test introduced in https://github.com/zonemaster/zonemaster-gui/pull/300 is quite slow as it is starting 3 tests, this reduces the polling interval in tests environment.
Run the e2e tests.
> make polling interval configurable

- package-lock.json
- package.json
- src/app/app.module.ts
Prevent translation caching when the translation are updated.
#283 
Use webpack `import` to load the translation, this adds a hash after the file name.
```
chunk {2} i18n-en-json-es2015.f8c41b236b7e77398141.js (i18n-en-json) 4.5 kB  [rendered]
chunk {2} i18n-en-json-es5.f8c41b236b7e77398141.js (i18n-en-json) 4.5 kB  [rendered]
chunk {1} i18n-da-json-es2015.561f401761dab618b7f2.js (i18n-da-json) 4.59 kB  [rendered]
chunk {1} i18n-da-json-es5.561f401761dab618b7f2.js (i18n-da-json) 4.59 kB  [rendered]
chunk {3} i18n-fi-json-es2015.28e026616c18fa840bf8.js (i18n-fi-json) 4.22 kB  [rendered]
chunk {3} i18n-fi-json-es5.28e026616c18fa840bf8.js (i18n-fi-json) 4.22 kB  [rendered]
chunk {6} i18n-sv-json-es2015.9c07614a0c8c0ee52778.js (i18n-sv-json) 4.87 kB  [rendered]
chunk {6} …
```
> use webpack import to load translations

- src/app/components/result/result.component.ts
Remove dependency on external bootstrap in HTML export.
#279 
Uses inline style instead of bootstrap.
Export a test result in HTML and open the export. The look should be close enough to the one using bootstrap.
> avoid using bootstrap for html export

- angular.json
- package-lock.json
- package.json
- src/app/components/faq/faq.component.css
- src/app/components/footer/footer.component.css
- src/app/components/footer/footer.component.html
- src/app/components/result/result.component.css
- src/polyfills.ts
- tsconfig.json
As Angular 11 is becoming EOL in two weeks this PR upgrades to Angular 12.
Maybe addresses #145 in a way
* Upgrade Angular to version 12
* Upgrade ng-bootstrap to version 8 to match the supported angular version
* Use fork awesome as a drop-in replacement  for  font awesome
* Upgrade some indirect dependencies with audit fix
* Remove github-fork-ribbon-css
Last install output with node 16, npm 8:
```
$ npm install
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm …
```
> Upgrade to angular12

- src/app/components/faq/faq.component.html
- src/app/components/faq/faq.component.ts
Use translated title instead of untranslated 'FAQ' for the FAQ page.
https://github.com/zonemaster/zonemaster-gui/pull/310#issuecomment-1111049570
* Translate 'FAQ' in `title` and `h1` (only affected locale is Finnish)
Check that the title of the page and the page header are translated for the FAQ page.
> translate faq title

- src/assets/i18n/sv.json
Give a friendlier title to the Swedish FAQ page.
Also see change introduced by #313.
Updates sv.json.
Open the FAQ page and see the heading in Swedish.
> Translates "FAQ" to Swedish

- src/app/components/history/history.component.ts
- src/app/interceptors/mock.interceptor.ts
* Avoid work around when parsing time.
* Move away from newly deprecated property.
Use new API property from https://github.com/zonemaster/zonemaster-backend/pull/967
Use `created_at` instead of `creation_time` as it is already in the right format.
* run a test
* query the history
* check that the time is correctly displayed and in the local timezone.
> use new property created_at when displaying history

- docs/Installation.md
This PR adds missing installation instructions for CentOS Linux 7 (CentOS). The support for CentOS was removed in the v2021.2 release, but was readded in v2022.1 release. The installation instructions were not added.
This is documentation only.
> Adds missing installation instructions for CentOS Linux 7 (GUI)

- e2e/FR02.e2e-spec.ts
- e2e/FR09.e2e-spec.ts
- e2e/navigation.e2e-spec.ts
- e2e/redirect.e2e-spec.ts
- src/app/app.module.ts
- src/app/components/form/form.component.ts
- src/app/components/navigation/navigation.component.html
It has been discussed to be able to easily pass a domain to test to Zonemaster GUI, without interacting with the form. The idea is to pass the domain name in the URL `/check/<domain>`.
The form's input field will be populated with this domain name and the form will be sent.
No option are currently passed. Only the domain. As I see it, we could extend this work to include options as GET parameters.
Addresses #200 and follow-up on #335
* New route `/check/<domain>`
* Redirect `/domain_check` to `/check`
* Redirect `/test/<test-id>` to `/result/<test-id>`
* access `/check/<domain>` and make sure the test is started for \<domain\>
* once on the result page, go back to the previous page, the form should be sent again and the results page should be loaded
* e2e tests have been added to test …
> Perform a test through the URL directly

- docs/Configuration.md
- src/assets/app.config.sample.json
Fix the documentation of the configuration.
The documented key for logo customization is `logo` while it should be `logoUrl`.
Change `logo` to `logoUrl` in the sample configuration and documentation.
Following the documentation to set a custom logo should work.
> fix logo customization key name in documentation

- scripts/faq.js
Fix FAQ navigation.
From mailing list
> when bringing up the FAQ, the FAQ direct links still want to go to  hostname/faq#q1 etc, not hostname/zonemaster/faq#q1
Use relative url from base url instead of absolute url.
* Start the gui with a custom base url, eg. `npm start -- --base-href "/zonemaster/"`
* Go to FAQ page and check that all links in the table of content work correctly.
> Fix FAQ links when serving from custom base

- docs/FAQ/gui-faq-da.md
- docs/FAQ/gui-faq-en.md
- docs/FAQ/gui-faq-es.md
- docs/FAQ/gui-faq-fi.md
- docs/FAQ/gui-faq-fr.md
- docs/FAQ/gui-faq-nb.md
- docs/FAQ/gui-faq-sv.md
FAQ 5 has the old mailing list address.
* Updated (corrected) mail address to mailing list.
* Added a comment that it is in fact a mailing list.
After the address I added "(moderated mailing list)" so that the send should know that. For Swedish I inserted a translated version, but for all other languages (da, es, fi, fr and nb) I inserted the same English text. Please add the correct wording for "your" language as a review comment to this PR.
2022-09-20: Turned the mail address into a mailto link, unless it already was.
On all, or most, installations of the GUI the wrong mail address is shown, and that results in an error.
Review the text.
> Updated all FAQs

- docs/FAQ/gui-faq-en.md
This PR proposes an update to the English FAQ.
Fixes #105 , #104 
- docs/FAQ/gui-faq-en.md : rewording, rephrasing, line breaks, max line length (110), reference links
N/A. Documentation only, to be reviewed.
> Update English FAQ

- e2e/FR05.e2e-spec.ts
- e2e/utils/app.utils.ts
- src/app/components/navigation/navigation.component.css
- src/app/components/navigation/navigation.component.html
Zonemaster supports more and more languages, and the GUI displays all of them on a row. This could lead to eating a lot of space. This PR replaces this row with a drop down menu (a \<select\> element) with an icon representing language selection (icon from [fork awesome](https://forkaweso.me/Fork-Awesome/icon/language/)).
Addresses a comment made when discussing the possibility to provide a new page for the "History" (PR #333) where it was pointed out that in some locale, the menu will span a lot of available space (almost eating on the language selection space).
Remove the horizontal language list in the header.
Use the new drop down language selection menu to switch across languages. The page should be updated accordingly.
> Use a drop down menu to select between languages

- src/app/app.component.css
- src/app/app.component.html
- src/styles.scss
Currently the footer part of the GUI might lay in the middle of the page. Especially if the screen resolution is too high and all the content fits on the page. This provides some CSS rules to make the inner content grow and push the footer to the bottom of the viewport.
n/a
CSS files
Run the GUI using this branch and check that the footer is always pushed to the bottom of the viewport, regardless of the screen size/resolution.
> Force footer to the viewport's bottom

- docs/FAQ/gui-faq-fr.md
This PR updates the French version of the FAQ.
Fixes #354 and follows up to #347.
- Update the French version of the FAQ to be in sync with the English version.
- Fix a few more spelling/grammar issues I found when going over the document.
It seems that this translation went way out of sync with the English version in a few places. Therefore, more edits were necessary compared to #347.
This is a documentation update.
> Update French version of the FAQ

- src/app/components/alert/alert.component.css
- src/app/components/alert/alert.component.html
- src/app/components/alert/alert.component.ts
- src/app/components/result/result.component.ts
- src/app/components/run-test/run-test.component.ts
Fix notifications behaviour.
* The notifications were displayed behind the navigation bar. (introduced in #365, spotted in https://github.com/zonemaster/zonemaster-gui/pull/364#pullrequestreview-1197123148)
* Success notifications were not displayed when the test was started from the result page (introduced in #257 / #300)
* Fix the alert container position to always be below the navigation bar.
* Always display the success notification after when the test succeed
Position
* Try fetching data for a non existing domain.
* Check that the notification is displayed.
* Try to scroll, the notification should be sticky below the navigation bar.
Notification not always displayed
* Create a test from the result page for a different domain
* Check that the success notification is displayed
> Fix notifications behaviour

- docs/Installation.md
- scripts/create_release.js
- zonemaster.conf-example
Since the migration to @angular/localize one bundle is generated per locale. This duplicates the assets.
While for the images it is sub-optimal but acceptable, for the configuration it is not. A user should not be required to update 6 times (or more in the future) the configuration, it is unpractical and error prone.
This PR changes the way the release zip is built to only use one assets folder. The asset folder is colocated with the locales folder to form the following architecture.
```
└── dist
├── assets
│   ├── css
│   ├── faqs
│   ├── favicon
│   └── images
├── da
├── en
├── es
├── fi
├── fr
├── nb
└── sv
```
This way the assets folder is only present once. Also it means that our previous documentation still applies as the configuration path as not changed. Users will not have to …
> Deduplicate the assets directory

- zonemaster.conf-example
Make URLs of the old URL scheme redirect to their counterparts in the new URL scheme.
Fixes #378.
This was first implemented in #349 and later broken in #376. 
...
Follow the testing instructions for #331, #332, #334, #339 and #349.
> Redirect deprecated path

- e2e/FR22.e2e-spec.ts
- src/app/components/result/result.component.css
- src/app/components/result/result.component.html
- src/app/components/result/result.component.ts
Improve accessibility of the result page
\-
The page looks and behave mostly the same way as before.
Notable changes:
* Wrap heading content into a button element that is itself in a heading element (`<h3><button>content</button></h3>`) for modules and testcases. Before that a heading with button role was used, as a result the element was loosing the semantic of the heading, this might have impacted people navigating by heading (eg. when using a braille or screen reader).
* Side effect of the change: improve keyboard navigation, the space key can now be used as well as the enter key to toggle module and test cases.
1. Navigate to a test result.
2. Open and close module and test case sections using the mouse.
3. Try doing the same using the keyboard (use tab to focus) using both the enter …
> Improve accessibility of the result page

- src/app/components/footer/footer.component.css
- src/app/components/footer/footer.component.html
- src/app/interceptors/mock.interceptor.ts
Fix alignment issue and improve accessibility.
\-
* Move footer links into a `<ul>` into a `<nav>`
* Add a link for documentation (was blocking https://github.com/zonemaster/zonemaster-gui/pull/383 and might be useful now that we have all public documentation in the same place)
* Fix alignment issue of the "Github" link and bad wrapping of the contact email on medium-small screen
* Use a  `<dl>` for program versions
* Improve color contrast for copyright text
Before
After
* Try to resize the viewport and check that the footer content is wrapping correctly.
> Improve footer

- docs/FAQ/gui-faq-da.md
- docs/FAQ/gui-faq-en.md
- docs/FAQ/gui-faq-es.md
- docs/FAQ/gui-faq-fi.md
- docs/FAQ/gui-faq-fr.md
- docs/FAQ/gui-faq-nb.md
- docs/FAQ/gui-faq-sv.md
- docs/TranslationGuide.md
- src/app/components/faq/faq.component.css
- src/app/components/faq/faq.component.ts
HTML files are created from markdown files. The current markdown code puts the anchor in a paragraph before the headline the link should link to. The solution does not create valid HTML. This PR resolves the issue.
All FAQ files in `docs/FAQ/gui-faq-*.md`, but no change of content.
Links in table of contents should go to the right question.
> Moves HTML anchor into header and creates valid HTML

- docs/FAQ/gui-faq-da.md
- docs/FAQ/gui-faq-en.md
- docs/FAQ/gui-faq-es.md
- docs/FAQ/gui-faq-fi.md
- docs/FAQ/gui-faq-fr.md
- docs/FAQ/gui-faq-nb.md
- docs/FAQ/gui-faq-sv.md
Fix broken links in FAQ.
Since v2023.1, the documentation architecture has changed. The links in the FAQ have not been updated.
* Update links pointing to the documentation.
* Fix broken heading in French FAQ.
* Remove useless trailing spaces.
* Check that the FAQ is correctly rendered.
* Check that the links are working.
> Fix documentation links in FAQ

- src/locale/messages.fi.xlf
This PR adjusts the language string for Finnish to remove a warning.
See https://github.com/zonemaster/zonemaster-gui/pull/420#pullrequestreview-1453288027
Verify that it works as expected.
> Adjuests the language code

- src/app/components/result/result.component.html
- src/app/components/result/result.component.ts
Fix the handling of unspecified messages following https://github.com/zonemaster/zonemaster-engine/pull/1302
based on #434
https://github.com/zonemaster/zonemaster-engine/pull/1302
The unspecified messages are displayed above other messages and not collapsed, regardless of the case of "Unspecified".
Relevant commit : 6a2a7ad9f145d2a88a6760793516e82031c0751f
Consult a test result of a domain tested after and before the change in https://github.com/zonemaster/zonemaster-engine/pull/1302.
What this PR fixes:
> Fix unspecified

- src/app/components/faq/faq.component.html
- src/locale/messages.xlf
Fix typo
https://github.com/zonemaster/zonemaster-gui/pull/450#discussion_r1462966192
\-
\-
> Fix typo in faq

- README.md
Update the readme to remove outdated information and make it more like other components readme.
\-
* Remove some contribution text
* Remove sécurity section because that has not be done for so long
* Remove duplicated acknowledgment to angular cli
* Remove release instructions
* Reorder some sections
* Update the build badge to use github action
\-
> Update gui readme

- package-lock.json
- package.json
- src/app/components/result/result.component.html
- src/app/components/result/result.component.ts
- src/app/components/run-test/run-test.component.ts
Following 2023.2 release IDN are always normalized in ASCII in database, to be more user friendly this PR convert them back to unicode to be displayed on the result page. It also displayed the ASCII form in bracket.
This changes nothing for non-IDN.
Fixes #198 
* Always convert domain to their Unicode form in title and result heading
* Also display ASCII domain for IDN
* The file name of the exported result uses the ASCII domain
Ideally make the test using a backend < 2023.2 and with backend >= 2023.2, to see how it behaves when the returned domain is in ASCII and Unicode, and check that both should behave the same way.
* Display the result of a test of an IDN
* The page title must contain the Unicode domain
* The result heading must show both the Unicode and ASCII domains
> Display idn in both ascii and unicode forms

- src/app/components/history/history.component.html
- src/app/components/history/history.component.ts
- src/app/components/result/result.component.html
- src/app/components/result/result.component.ts
No indication (visual or not) are given to the user to signal that the new test results have been fetched.
Fixes #242 
Close the history modal when a link is clicked and move focus to the result heading (h2).
Limitation (maybe future work) : if the result request takes some time the focus would be moved to the old title and there would not be a indication when the new results have been received.
(Better to test with a screen reader)
* Open the history
* Tab to a test link
* Press enter
* The history modal should close itself and the focus should be move the title (containing the domain name and being described by the creation time)
> Close history modal

- Changes
- package.json
- src/app/components/footer/footer.component.html
- src/environments/version.ts
This PR is a preparation for v2024.2 release. See https://github.com/zonemaster/zonemaster/blob/develop/docs/internal/maintenance/ReleaseProcess-release.md#7-set-version-number-for-gui
The footer file contains a link to the documentation, which is updated here.
*  package.json
* Changes
* src/app/components/footer/footer.component.html
Review.
> Preparation for v2024.2 release (GUI)
